name: "Validate PR title"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # https://github.com/amannn/action-semantic-pull-request#configuration
        with:
          wip: true
          ignoreLabels: |
            bot
            ignore-semantic-pull-request
          scopes: |
            deps
            deps-dev
